language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-mirage.sh
script: bash -ex .travis-mirage.sh
sudo: required
dist: trusty
addons:
  apt:
    sources:
    - avsm
    packages:
    - ocaml
    - ocaml-base
    - ocaml-native-compilers
    - ocaml-compiler-libs
    - ocaml-interp
    - ocaml-base-nox
    - ocaml-nox
    - camlp4
    - camlp4-extra
    - time
    - libxen-dev
env:
  - BASE_REMOTE=https://github.com/talex5/opam-repository.git#qubes-vchan FORK_USER=talex5 FORK_BRANCH=unikernel OCAML_VERSION=4.02 MIRAGE_BACKEND=xen PINS="mirage-xen:https://github.com/talex5/mirage-platform.git#mm mirage-nat:https://github.com/talex5/mirage-nat.git#simplify-checksum tcpip:https://github.com/mirage/mirage-tcpip.git"
